#Server
server:
  port: 8080
  contextPath: /contextPath
#Logging
logging:
    level:
      org.springframework.web: DEBUG
      com.cooksdev: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#output to a temp_folder/file
#logging.file=${java.io.tmpdir}/application.log

#output to a file
#logging.file=/Users/mkyong/application.log


app:
  name: Roma
  age: 10

